### ISSUE TITLE
テスト実行時のオプションの適用方法の実行例ドキュメントの要望

### ISSUE THREAD

**Issue by kabayan55** [clear-code/pikzie#10]
# 概要

https://github.com/kabayan55/pikzie/blob/master/README.ja
上記のページ(README.ja)の「オプション」の項目を読んで、テスト実行時にオプションを適用しようと思ったのですが、その方法がわかりませんでした。
# 手順

```
python --priority run-test.py 
```

と実行した結果、

```
Unknown option: --
usage: /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

と出力されました。
# 期待する結果

例えば、
python run-test.py [option]
と書いてあれば、間違えずに実行ができると思います。

**Comment by kou** [comment]
提案ありがとうございます。実際に自分がやってうまくいかなかったケースが書かれていてわかりやすかったです。こういう情報を含めるのはとてもよいことだと思います。

こんな感じ https://github.com/clear-code/pikzie/commit/b4e4688e7aaa3b5010b6aed5132f8f25e866089c で追記してみました。
