### ISSUE TITLE
README.jaにおけるrun-test.pyの実行権限について

### ISSUE THREAD

**Issue by kabayan55** [clear-code/pikzie#11]
# 概要

テストの実行を試みたのですが、実行できませんでした。
# 手順

https://github.com/kabayan55/pikzie/blob/master/README.ja
上記ページ(README.ja)の「使い方」の項目を読み、run-test.pyを作成しました。
その際、

``` python
#!/usr/bin/env python

  import sys
  import os

  base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
  sys.path.insert(0, os.path.join(base_dir, "lib"))
  sys.path.insert(0, base_dir)

  import pikzie

  sys.exit(pikzie.Tester().run())
```

をコピー&ペーストしました。

その後、

```
% test/run-test.py
```

を実行しました。
# 結果

```
-bash: test/run-test.py: Permission denied
```

と表示され、実行ができませんでした。
# 期待する結果

README.jaの「使い方」の項目に
「run-test.pyを実行権限のある状態にしてからテストを実行してください」
という内容のことを、書いていただけると、実行がスムーズにいくと思います。

**Comment by okkez** [comment]
Fixed in: 9693946c8, 441e2f78

Thank you for your report for this issue!!
