### ISSUE TITLE
Bug: fails to handle KeyboardInterrupt properly.

### ISSUE THREAD

**Issue by fujimotos** [clear-code/pikzie#24]
From reading pikzie/core.py, Pikzie seems to support the 'abort the
test execution with CTRL-C' feature (as other testing frameworks do).

However, the problem is that it does not work well right now.
In fact, hitting CTRL-C while testing reveals that the testing process
just continues the execution of test cases, and won't exit.

These pull-requests below are my attempt to address this issue:
- Fix: call the correct handler on KeyboardInterrupt. [#21]
- Notify the KeyboardInterupt to the parent context. [#22]
- Make TestCaseRunner notice the keyboard interruption. [#23] 

With these patches applied, the keybord interruption will work nicely.

**Comment by kou** [comment]
Thanks for your report.
I've merged all your pull requests and released a new version.
