### ISSUE TITLE
New Feature: Support a context manager for exception-related testing

### ISSUE THREAD

**Issue by fujimotos** [clear-code/pikzie#31]
Some Pythonic testing frameworks (like `unittest` or `pytest`) allow users to
express exception-related conditions through "with" blocks. For example,
with `unittest`, we can check if a non-existent key raises KeyError as:

``` python
def test_deleted_item(self):
    with self.assertRaises(KeyError):
        self.table.get_item('deleted')
```

Below is the equivalent example using `pytest`:

``` python
def test_deleted_item(table):
    with pytest.raises(KeyError):
        table.get_item('deleted')
```

Now, I'm trying to add the same functionality to pikzie. Here is a patch: 

> Implement a context manager for exception-related testing [#30]

What do you think about this feature or patch? Any feedback is welcome.

**Comment by kou** [comment]
It's reasonable. I've merged #30.
